[package]
name = "eclipse_heart"
version = "0.1.0"
edition = "2021"
default-run = "eclipse_heart"

[dependencies]
macroquad = "=0.4.16"
macroquad-toolkit = { path = "../macroquad-toolkit" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
arboard = "3.6"
